package com.ssomar.score.features;

import com.ssomar.score.config.GeneralConfig;
import com.ssomar.score.features.lang.FeatureSettingsSCoreEN;
import com.ssomar.score.features.lang.FeatureSettingsSCoreFR;
import com.ssomar.score.features.lang.FeatureSettingsSCoreRU;
import com.ssomar.score.features.lang.FeatureSettingsSCoreZH;
import org.bukkit.Material;

public enum FeatureSettingsSCore implements FeatureSettingsInterface {

    HARDNESS(getFeatureSettings("HARDNESS")),
    SPROJECTILE(getFeatureSettings("SPROJECTILE")),
    VARIABLE(getFeatureSettings("VARIABLE")),
    aboveValue(getFeatureSettings("aboveValue")),
    activator(getFeatureSettings("activator")),
    activators(getFeatureSettings("activators")),
    activeTitle(getFeatureSettings("activeTitle")),
    amount(getFeatureSettings("amount")),
    amplifier(getFeatureSettings("amplifier")),
    armorTrim(getFeatureSettings("armorTrim")),
    aroundBlock(getFeatureSettings("AroundBlock")),
    aroundBlockCdts(getFeatureSettings("blockAroundCdts")),
    attribute(getFeatureSettings("attribute")),
    attributes(getFeatureSettings("attributes")),
    bannerSettings(getFeatureSettings("bannerSettings")),
    blockType(getFeatureSettings("blockType")),
    blockTypeMustBe(getFeatureSettings("blockTypeMustBe")),
    blocks(getFeatureSettings("blocks")),
    bounce(getFeatureSettings("bounce")),
    cancelActionEnchantInAnvil(getFeatureSettings("cancel-enchant-anvil")),
    cancelActionRenameInAnvil(getFeatureSettings("cancel-rename-anvil")),
    cancelAllCraft(getFeatureSettings("cancel-item-craft")),
    cancelAnvil(getFeatureSettings("cancel-anvil")),
    cancelArmorStand(getFeatureSettings("cancel-armorstand")),
    cancelBeacon(getFeatureSettings("cancel-beacon")),
    cancelBrewing(getFeatureSettings("cancel-brewing")),
    cancelCartography(getFeatureSettings("cancel-cartography")),
    cancelComposter(getFeatureSettings("cancel-composter")),
    cancelConsumption(getFeatureSettings("cancel-consumption")),
    cancelCraft(getFeatureSettings("cancel-item-craft-no-custom")),
    cancelDepositInChest(getFeatureSettings("cancel-deposit-in-chest")),
    cancelDepositInFurnace(getFeatureSettings("cancel-deposit-in-furnace")),
    cancelDispenser(getFeatureSettings("cancel-dispenser")),
    cancelDropper(getFeatureSettings("cancel-dropper")),
    cancelEnchant(getFeatureSettings("cancel-enchant")),
    cancelEventIfError(getFeatureSettings("cancelEventIfError")),
    cancelEventIfInCooldown(getFeatureSettings("cancelEventIfInCooldown")),
    cancelEventIfMaxReached(getFeatureSettings("cancelEventIfMaxReached")),
    cancelEventIfNoPermission(getFeatureSettings("cancelEventIfNoPermission")),
    cancelEventIfNotValid(getFeatureSettings("cancelEventIfNotValid")),
    cancelEvents(getFeatureSettings("cancelEvents")),
    cancelGrindStone(getFeatureSettings("cancel-grind-stone")),
    cancelHopper(getFeatureSettings("cancel-hopper")),
    cancelHorn(getFeatureSettings("cancel-horn")),
    cancelHorse(getFeatureSettings("cancel-horse")),
    cancelItemBurn(getFeatureSettings("cancel-item-burn")),
    cancelItemDeleteByCactus(getFeatureSettings("cancel-item-delete-by-cactus")),
    cancelItemDeleteByLightning(getFeatureSettings("cancel-item-delete-by-lightning")),
    cancelItemDrop(getFeatureSettings("cancel-item-drop")),
    cancelItemFrame(getFeatureSettings("cancel-item-frame")),
    cancelItemPlace(getFeatureSettings("cancel-item-place")),
    cancelLectern(getFeatureSettings("cancel-lectern")),
    cancelLoom(getFeatureSettings("cancel-loom")),
    cancelDecoratedPot(getFeatureSettings("cancel-decorated-pot")),
    cancelCrafter(getFeatureSettings("cancel-crafter")),
    cancelMerchant(getFeatureSettings("cancel-merchant")),
    cancelSmithingTable(getFeatureSettings("cancel-smithing-table")),
    cancelStoneCutter(getFeatureSettings("cancel-stone-cutter")),
    cancelSwapHand(getFeatureSettings("cancel-swap-hand")),
    cancelToolInteractions(getFeatureSettings("cancel-tool-interactions")),
    charged(getFeatureSettings("charged")),
    color(getFeatureSettings("color")),
    containerContent(getFeatureSettings("containerContent")),
    colors(getFeatureSettings("colors")),
    comparator(getFeatureSettings("comparator")),
    cooldown(getFeatureSettings("cooldown")),
    cooldownMsg(getFeatureSettings("cooldownMsg")),
    critical(getFeatureSettings("critical")),
    customModelData(getFeatureSettings("customModelData")),
    customName(getFeatureSettings("customName")),
    customNameVisible(getFeatureSettings("customNameVisible")),
    damage(getFeatureSettings("damage")),
    default_double(getFeatureSettings("default")),
    default_list(getFeatureSettings("default")),
    default_string(getFeatureSettings("default")),
    delay(getFeatureSettings("delay")),
    delayInTick(getFeatureSettings("delayInTick")),
    despawnDelay(getFeatureSettings("despawnDelay")),
    detailedBlocks(getFeatureSettings("detailedBlocks")),
    detailedEffects(getFeatureSettings("detailedEffects")),
    detailedItems(getFeatureSettings("detailedItems")),
    detailedSlots(getFeatureSettings("detailedSlots")),
    displayCooldownMessage(getFeatureSettings("displayCooldownMessage")),
    displayNameDrop(getFeatureSettings("displayNameDrop")),
    dropOptions(getFeatureSettings("dropOptions")),
    duration(getFeatureSettings("duration")),
    eastValue(getFeatureSettings("eastValue")),
    effects(getFeatureSettings("effects")),
    enableArmorTrim(getFeatureSettings("enableArmorTrim")),
    enchantment(getFeatureSettings("enchantment")),
    enchantmentWithLevel(getFeatureSettings("enchantmentWithLevel")),
    enchantments(getFeatureSettings("enchantments")),
    entityType(getFeatureSettings("entityType")),
    errorMessage(getFeatureSettings("errorMessage")),
    errorMsg(getFeatureSettings("errorMsg")),
    executableItem(getFeatureSettings("executableItem")),
    itemsAdder(getFeatureSettings("itemsAdder")),
    fadeColors(getFeatureSettings("fadeColors")),
    fireworkFeatures(getFeatureSettings("fireworkFeatures")),
    fireworkExplosion(getFeatureSettings("fireworkExplosion")),
    fireworkExplosions(getFeatureSettings("fireworkExplosions")),
    hasTrail(getFeatureSettings("hasTrail")),
    hasTwinkle(getFeatureSettings("hasTwinkle")),
    for_(getFeatureSettings("for")),
    giveFirstJoin(getFeatureSettings("giveFirstJoin")),
    giveFirstJoinAmount(getFeatureSettings("giveFirstJoinAmount")),
    giveFirstJoinFeatures(getFeatureSettings("giveFirstJoin")),
    giveFirstJoinSlot(getFeatureSettings("giveFirstJoinSlot")),
    glowDrop(getFeatureSettings("glowDrop")),
    glowDropColor(getFeatureSettings("glowDropColor")),
    glowing(getFeatureSettings("glowing")),
    gravity(getFeatureSettings("gravity")),
    hasExecutableItem(getFeatureSettings("hasExecutableItem")),
    hasIcon(getFeatureSettings("hasIcon")),
    hasItem(getFeatureSettings("hasItem")),
    hasParticles(getFeatureSettings("hasParticles")),
    headDBID(getFeatureSettings("headDBID")),
    headFeatures(getFeatureSettings("headFeatures")),
    headValue(getFeatureSettings("headValue")),
    hideArmorTrim(getFeatureSettings("hideArmorTrim")),
    hideAttributes(getFeatureSettings("hideAttributes")),
    hideDestroys(getFeatureSettings("hideDestroys")),
    hideDye(getFeatureSettings("hideDye")),
    hideEnchantments(getFeatureSettings("hideEnchantments")),
    hidePlacedOn(getFeatureSettings("hidePlacedOn")),
    hideAdditionalTooltip(getFeatureSettings("hideAdditionalTooltip")),
    hideTooltip(getFeatureSettings("hideToolTip")),
    hidePotionEffects(getFeatureSettings("hidePotionEffects")),
    hideUnbreakable(getFeatureSettings("hideUnbreakable")),
    hideUsage(getFeatureSettings("hideUsage")),
    hiders(getFeatureSettings("hiders")),
    icon(getFeatureSettings("icon")),
    ifAdult(getFeatureSettings("ifAdult")),
    ifBaby(getFeatureSettings("ifBaby")),
    ifBlockAge(getFeatureSettings("ifBlockAge")),
    ifBlockLocationX(getFeatureSettings("ifBlockLocationX")),
    ifBlockLocationY(getFeatureSettings("ifBlockLocationY")),
    ifBlockLocationZ(getFeatureSettings("ifBlockLocationZ")),
    ifBlocking(getFeatureSettings("ifBlocking")),
    ifCanBreakTargetedBlock(getFeatureSettings("ifCanBreakTargetedBlock")),
    ifContainerContains(getFeatureSettings("ifContainerContains")),
    ifContainerContainsEI(getFeatureSettings("ifContainerContainsEI")),
    ifContainerContainsSellableItems(getFeatureSettings("ifContainerContainsSellableItems")),
    ifContainerEmpty(getFeatureSettings("ifContainerEmpty")),
    ifContainerNotEmpty(getFeatureSettings("ifContainerNotEmpty")),
    ifCrossbowMustBeCharged(getFeatureSettings("ifCrossbowMustBeCharged")),
    ifCrossbowMustNotBeCharged(getFeatureSettings("ifCrossbowMustNotBeCharged")),
    ifCursorDistance(getFeatureSettings("ifCursorDistance")),
    ifDurability(getFeatureSettings("ifDurability")),
    ifEntityHealth(getFeatureSettings("ifEntityHealth")),
    ifFlying(getFeatureSettings("ifFlying")),
    ifFromSpawner(getFeatureSettings("ifFromSpawner")),
    ifFrozen(getFeatureSettings("ifFrozen")),
    ifGliding(getFeatureSettings("ifGliding")),
    ifGlowing(getFeatureSettings("ifGlowing")),
    ifHasAI(getFeatureSettings("ifHasAI")),
    ifHasEnchant(getFeatureSettings("ifHasEnchant")),
    ifHasExecutableItems(getFeatureSettings("ifHasExecutableItems")),
    ifHasItems(getFeatureSettings("ifHasItems")),
    ifHasNotEnchant(getFeatureSettings("ifHasNotEnchant")),
    ifHasNotExecutableItems(getFeatureSettings("ifHasNotExecutableItems")),
    ifHasNotItems(getFeatureSettings("ifHasNotItems")),
    ifHasPermission(getFeatureSettings("ifHasPermission")),
    ifHasSaddle(getFeatureSettings("ifHasSaddle")),
    ifHasTag(getFeatureSettings("ifHasTag")),
    ifInBiome(getFeatureSettings("ifInBiome")),
    ifInRegion(getFeatureSettings("ifInRegion")),
    ifInWorld(getFeatureSettings("ifInWorld")),
    ifInvulnerable(getFeatureSettings("ifInvulnerable")),
    ifIsInTheAir(getFeatureSettings("ifIsInTheAir")),
    ifIsInTheBlock(getFeatureSettings("ifIsInTheBlock")),
    ifIsNotInTheAir(getFeatureSettings("ifIsNotInTheAir")),
    ifIsNotInTheBlock(getFeatureSettings("ifIsNotInTheBlock")),
    ifIsNotOnFire(getFeatureSettings("ifIsNotOnFire")),
    ifIsNotOnTheBlock(getFeatureSettings("ifIsNotOnTheBlock")),
    ifIsOnFire(getFeatureSettings("ifIsOnFire")),
    ifIsOnTheBlock(getFeatureSettings("ifIsOnTheBlock")),
    ifIsPowered(getFeatureSettings("ifIsPowered")),
    ifLightLevel(getFeatureSettings("ifLightLevel")),
    ifMustBeNatural(getFeatureSettings("ifMustBeNatural")),
    ifMustBeNotNatural(getFeatureSettings("ifMustBeNotNatural")),
    ifMustBeNotPowered(getFeatureSettings("ifMustBeNotPowered")),
    ifName(getFeatureSettings("ifName")),
    ifNamed(getFeatureSettings("ifNamed")),
    ifNeedPlayerConfirmation(getFeatureSettings("ifNeedPlayerConfirmation")),
    ifNoPlayerMustBeOnTheBlock(getFeatureSettings("ifNoPlayerMustBeOnTheBlock")),
    ifNotBlocking(getFeatureSettings("ifNotBlocking")),
    ifNotEntityType(getFeatureSettings("ifNotEntityType")),
    ifNotFlying(getFeatureSettings("ifNotFlying")),
    ifNotFromSpawner(getFeatureSettings("ifNotFromSpawner")),
    ifNotGliding(getFeatureSettings("ifNotGliding")),
    ifNotHasAI(getFeatureSettings("ifNotHasAI")),
    ifNotHasPermission(getFeatureSettings("ifNotHasPermission")),
    ifNotHasSaddle(getFeatureSettings("ifNotHasSaddle")),
    ifNotHasTag(getFeatureSettings("ifNotHasTag")),
    ifNotInBiome(getFeatureSettings("ifNotInBiome")),
    ifNotInRegion(getFeatureSettings("ifNotInRegion")),
    ifNotInWorld(getFeatureSettings("ifNotInWorld")),
    ifNotNamed(getFeatureSettings("ifNotNamed")),
    ifNotOwnerOfTheEI(getFeatureSettings("ifNotOwnerOfTheEI")),
    ifNotSneaking(getFeatureSettings("ifNotSneaking")),
    ifNotSprinting(getFeatureSettings("ifNotSprinting")),
    ifNotStunned(getFeatureSettings("ifNotStunned")),
    ifNotSwimming(getFeatureSettings("ifNotSwimming")),
    ifNotTamed(getFeatureSettings("ifNotTamed")),
    ifNotTargetBlock(getFeatureSettings("ifNotTargetBlock")),
    ifOnFire(getFeatureSettings("ifOnFire")),
    ifOwnerOfTheEI(getFeatureSettings("ifOwnerOfTheEI")),
    ifPlantFullyGrown(getFeatureSettings("ifPlantFullyGrown")),
    ifPlantNotFullyGrown(getFeatureSettings("ifPlantNotFullyGrown")),
    ifPlayerEXP(getFeatureSettings("ifPlayerEXP")),
    ifPlayerFoodLevel(getFeatureSettings("ifPlayerFoodLevel")),
    ifPlayerHasEffect(getFeatureSettings("ifPlayerHasEffect")),
    ifPlayerHasEffectEquals(getFeatureSettings("ifPlayerHasEffectEquals")),
    ifPlayerHealth(getFeatureSettings("ifPlayerHealth")),
    ifPlayerLevel(getFeatureSettings("ifPlayerLevel")),
    ifPlayerMounts(getFeatureSettings("ifPlayerMounts")),
    ifPlayerMustBeInHisTown(getFeatureSettings("ifPlayerMustBeInHisTown")),
    ifPlayerMustBeOnHisClaim(getFeatureSettings("ifPlayerMustBeOnHisClaim")),
    ifPlayerMustBeOnHisClaimOrWilderness(getFeatureSettings("ifPlayerMustBeOnHisClaimOrWilderness")),
    ifPlayerMustBeOnHisIsland(getFeatureSettings("ifPlayerMustBeOnHisIsland")),
    ifPlayerMustBeOnHisPlot(getFeatureSettings("ifPlayerMustBeOnHisPlot")),
    ifPlayerMustBeOnTheBlock(getFeatureSettings("ifPlayerMustBeOnTheBlock")),
    ifPlayerNotHasEffect(getFeatureSettings("ifPlayerNotHasEffect")),
    ifPlayerNotMounts(getFeatureSettings("ifPlayerNotMounts")),
    ifPosX(getFeatureSettings("ifPosX")),
    ifPosY(getFeatureSettings("ifPosY")),
    ifPosZ(getFeatureSettings("ifPosZ")),
    ifPowered(getFeatureSettings("ifPowered")),
    ifSneaking(getFeatureSettings("ifSneaking")),
    ifSprinting(getFeatureSettings("ifSprinting")),
    ifStunned(getFeatureSettings("ifStunned")),
    ifSwimming(getFeatureSettings("ifSwimming")),
    ifTamed(getFeatureSettings("ifTamed")),
    ifTargetBlock(getFeatureSettings("ifTargetBlock")),
    ifUsage(getFeatureSettings("ifUsage")),
    ifWeather(getFeatureSettings("ifWeather")),
    ifWorldTime(getFeatureSettings("ifWorldTime")),
    incendiary(getFeatureSettings("incendiary")),
    invisible(getFeatureSettings("invisible")),
    isAmbient(getFeatureSettings("isAmbient")),
    isCooldownInTicks(getFeatureSettings("isCooldownInTicks")),
    items(getFeatureSettings("items")),
    knockbackStrength(getFeatureSettings("knockbackStrength")),
    level(getFeatureSettings("level")),
    lifeTime(getFeatureSettings("lifeTime")),
    lockedInventory(getFeatureSettings("locked-in-inventory")),
    loop(getFeatureSettings("loop")),
    magicID(getFeatureSettings("magicID")),
    material(getFeatureSettings("material")),
    materialAndTags(getFeatureSettings("materialAndTags")),
    maxUsePerDay(getFeatureSettings("maxUsePerDay")),
    messageIfMaxReached(getFeatureSettings("messageIfMaxReached")),
    messageIfNotValid(getFeatureSettings("messageIfNotValid")),
    messageIfNotValidForTarget(getFeatureSettings("messageIfNotValidForTarget")),
    modification_double(getFeatureSettings("modification")),
    modification_string(getFeatureSettings("modification")),
    multiChoices(getFeatureSettings("multi-choices")),
    name(getFeatureSettings("name")),
    northValue(getFeatureSettings("northValue")),
    notExecutableItem(getFeatureSettings("notExecutableItem")),
    object(getFeatureSettings("object")),
    operation(getFeatureSettings("operation")),
    part1(getFeatureSettings("part1")),
    part2(getFeatureSettings("part2")),
    particle(getFeatureSettings("particle")),
    particles(getFeatureSettings("particles")),
    particlesAmount(getFeatureSettings("particlesAmount")),
    particlesDelay(getFeatureSettings("particlesDelay")),
    particlesDensity(getFeatureSettings("particlesDensity")),
    particlesOffSet(getFeatureSettings("particlesOffSet")),
    particlesSpeed(getFeatureSettings("particlesSpeed")),
    particlesType(getFeatureSettings("particlesType")),
    pattern(getFeatureSettings("pattern")),
    patterns(getFeatureSettings("patterns")),
    pausePlaceholdersConditions(getFeatureSettings("pausePlaceholdersConditions")),
    pauseWhenOffline(getFeatureSettings("pauseWhenOffline")),
    enableVisualCooldown(getFeatureSettings("enableVisualCooldown")),
    period(getFeatureSettings("period")),
    periodInTicks(getFeatureSettings("periodInTicks")),
    pickupStatus(getFeatureSettings("pickupStatus")),
    pierceLevel(getFeatureSettings("pierceLevel")),
    placeholderCondition(getFeatureSettings("placeholderCondition")),
    placeholderConditionCmds(getFeatureSettings("placeholderConditionCmds")),
    placeholdersConditions(getFeatureSettings("placeholdersConditions")),
    potionColor(getFeatureSettings("potionColor")),
    potionEffect(getFeatureSettings("potionEffect")),
    potionEffectType(getFeatureSettings("potionEffectType")),
    potionEffects(getFeatureSettings("potionEffects")),
    potionExtended(getFeatureSettings("potionExtended")),
    potionSettings(getFeatureSettings("potionSettings")),
    potionType(getFeatureSettings("potionType")),
    potionUpgraded(getFeatureSettings("potionUpgraded")),
    radius(getFeatureSettings("radius")),
    redstoneColor(getFeatureSettings("redstoneColor")),
    removeWhenHitBlock(getFeatureSettings("removeWhenHitBlock")),
    requiredExecutableItem(getFeatureSettings("requiredExecutableItem")),
    requiredExecutableItems(getFeatureSettings("requiredExecutableItems")),
    requiredExperience(getFeatureSettings("requiredExperience")),
    requiredGroups(getFeatureSettings("requiredGroups")),
    requiredItem(getFeatureSettings("requiredItem")),
    requiredItems(getFeatureSettings("requiredItems")),
    requiredLevel(getFeatureSettings("requiredLevel")),
    requiredMagic(getFeatureSettings("requiredMagic")),
    requiredMagics(getFeatureSettings("requiredMagics")),
    requiredMana(getFeatureSettings("requiredMana")),
    requiredMoney(getFeatureSettings("requiredMoney")),
    restrictions(getFeatureSettings("restrictions")),
    silent(getFeatureSettings("silent")),
    slot(getFeatureSettings("slot")),
    southValue(getFeatureSettings("southValue")),
    stopCheckingOtherConditionsIfNotValid(getFeatureSettings("stopCheckingOtherConditionsIfNotValid")),
    string(getFeatureSettings("string")),
    subPattern(getFeatureSettings("subPattern")),
    subPatterns(getFeatureSettings("subPatterns")),
    tags(getFeatureSettings("tags")),
    title(getFeatureSettings("title")),
    titleAdjustement(getFeatureSettings("titleAdjustement")),
    titleOptions(getFeatureSettings("titleOptions")),
    trimMaterial(getFeatureSettings("trimMaterial")),
    type(getFeatureSettings("type")),
    underValue(getFeatureSettings("underValue")),
    usageConditions(getFeatureSettings("usageConditions")),
    usePerDay(getFeatureSettings("usePerDay")),
    uuid(getFeatureSettings("uuid")),
    variable(getFeatureSettings("variable")),
    variableName(getFeatureSettings("variableName")),
    variableUpdate(getFeatureSettings("variableUpdate")),
    variables(getFeatureSettings("variables")),
    variablesModification(getFeatureSettings("variablesModification")),
    velocity(getFeatureSettings("velocity")),
    visualFire(getFeatureSettings("visualFire")),
    visualItem(getFeatureSettings("visualItem")),
    westValue(getFeatureSettings("westValue")),
    bookFeatures(getFeatureSettings("bookFeatures")),
    pages(getFeatureSettings("pages")),
    author(getFeatureSettings("author")),
    equippableFeatures(getFeatureSettings("equippableFeatures")),
    enableSound(getFeatureSettings("enableSound")),
    sound(getFeatureSettings("sound")),
    equipModel(getFeatureSettings("equipModel")),
    cameraOverlay(getFeatureSettings("cameraOverlay")),
    damageableOnHurt(getFeatureSettings("damageableOnHurt")),
    dispensable(getFeatureSettings("dispensable")),
    swappable(getFeatureSettings("swappable")),
    allowedEntities(getFeatureSettings("allowedEntities")),
    repairableFeatures(getFeatureSettings("repairableFeatures")),
    repairCost(getFeatureSettings("repairCost")),
    glider(getFeatureSettings("glider")),
    itemModel(getFeatureSettings("itemModel")),
    tooltipModel(getFeatureSettings("tooltipModel")),
    toolRules(getFeatureSettings("toolRules")),
    toolRule(getFeatureSettings("toolRule")),
    miningSpeed(getFeatureSettings("miningSpeed")),
    enable(getFeatureSettings("enable")),
    defaultMiningSpeed(getFeatureSettings("defaultMiningSpeed")),
    correctForDrops(getFeatureSettings("correctForDrops")),
    materials(getFeatureSettings("blocks")),
    damagePerBlock(getFeatureSettings("damagePerBlock")),
    instrumentFeatures(getFeatureSettings("instrumentFeatures")),
    instrument(getFeatureSettings("instrument")),
    chargedProjectiles(getFeatureSettings("chargedProjectiles")),
    hitSound(getFeatureSettings("hitSound")),
    useCooldownFeatures(getFeatureSettings("useCooldownFeatures")),
    cooldownGroup(getFeatureSettings("cooldownGroup")),
    vanillaUseCooldown(getFeatureSettings("vanillaUseCooldown")),
    typeTarget(getFeatureSettings("typeTarget")),
    detailedClick(getFeatureSettings("detailedClick")),
    usageModification(getFeatureSettings("usageModification")),
    cancelEvent(getFeatureSettings("cancelEvent")),
    noActivatorRunIfTheEventIsCancelled(getFeatureSettings("noActivatorRunIfTheEventIsCancelled")),
    silenceOutput(getFeatureSettings("silenceOutput")),
    mustBeAProjectileLaunchWithTheSameEI(getFeatureSettings("mustBeAProjectileLaunchWithTheSameEI")),
    desactiveDrops(getFeatureSettings("desactiveDrops")),
    option(getFeatureSettings("option")),
    cooldownOptions(getFeatureSettings("cooldownOptions")),
    globalCooldownOptions(getFeatureSettings("globalCooldownOptions")),
    detailedEntities(getFeatureSettings("detailedEntities")),
    detailedTargetEntities(getFeatureSettings("detailedTargetEntities")),
    detailedTargetBlocks(getFeatureSettings("detailedTargetBlocks")),
    detailedDamageCauses(getFeatureSettings("detailedDamageCauses")),
    detailedCommands(getFeatureSettings("detailedCommands")),
    detailedMessagesContains(getFeatureSettings("detailedMessagesContains")),
    detailedMessagesEquals(getFeatureSettings("detailedMessagesEquals")),
    detailedInventories(getFeatureSettings("detailedInventories")),
    mustBeItsOwnInventory(getFeatureSettings("mustBeItsOwnInventory")),
    commands_player(getFeatureSettings("commands")),
    commands_block(getFeatureSettings("commands")),
    targetCommands(getFeatureSettings("targetCommands")),
    entityCommands(getFeatureSettings("entityCommands")),
    blockCommands(getFeatureSettings("blockCommands")),
    blockCommands_target_block(getFeatureSettings("blockCommands")),
    playerCommands(getFeatureSettings("playerCommands")),
    ownerCommands(getFeatureSettings("ownerCommands")),
    consoleCommands(getFeatureSettings("consoleCommands")),
    targetPlayerCommands(getFeatureSettings("targetPlayerCommands")),
    targetEntityCommands(getFeatureSettings("targetEntityCommands")),
    targetBlockCommands(getFeatureSettings("targetBlockCommands")),
    displayCommands(getFeatureSettings("displayCommands")),
    playerConditions(getFeatureSettings("playerConditions")),
    targetConditions(getFeatureSettings("targetConditions")),
    entityConditions(getFeatureSettings("entityConditions")),
    blockConditions(getFeatureSettings("blockConditions")),
    worldConditions(getFeatureSettings("worldConditions")),
    itemConditions(getFeatureSettings("itemConditions")),
    customConditions(getFeatureSettings("customConditions")),
    ownerConditions(getFeatureSettings("ownerConditions")),
    targetBlockConditions(getFeatureSettings("targetBlockConditions")),
    targetPlayerConditions(getFeatureSettings("targetPlayerConditions")),
    targetEntityConditions(getFeatureSettings("targetEntityConditions")),
    displayConditions_conditions(getFeatureSettings("displayConditions")),
    containsMineInCube(getFeatureSettings("containsMineInCube")),
    playerCooldownOptions(getFeatureSettings("playerCooldownOptions")),
    entityCooldownOptions(getFeatureSettings("entityCooldownOptions")),
    isRefreshableClean(getFeatureSettings("isRefreshableClean")),
    refreshTag(getFeatureSettings("refreshTagDoNotEdit")),
    otherEICooldowns(getFeatureSettings("otherEICooldowns")),
    cooldown_activators(getFeatureSettings("activators")),
    canBeUsedOnlyByTheOwner(getFeatureSettings("canBeUsedOnlyByTheOwner")),
    cancelEventIfNotOwner(getFeatureSettings("cancelEventIfNotOwner")),
    onlyOwnerBlackListedActivators(getFeatureSettings("onlyOwnerBlackListedActivators")),
    EXECUTABLEITEM(getFeatureSettings("EXECUTABLEITEM")),
    lore(getFeatureSettings("lore")),
    glow(getFeatureSettings("glow")),
    glowDuration(getFeatureSettings("glowDuration")),
    disableEnchantGlide(getFeatureSettings("disableEnchantGlide")),
    disableStack(getFeatureSettings("disableStack")),
    customStackSize(getFeatureSettings("customStackSize")),
    keepItemOnDeath(getFeatureSettings("keepItemOnDeath")),
    storeItemInfo(getFeatureSettings("storeItemInfo")),
    keepDefaultAttributes(getFeatureSettings("keepDefaultAttributes")),
    ignoreKeepDefaultAttributesFeature(getFeatureSettings("ignoreKeepDefaultAttributesFeature")),
    unbreakable(getFeatureSettings("unbreakable")),
    usage(getFeatureSettings("usage")),
    usageLimit(getFeatureSettings("usageLimit")),
    customModelData_ei(getFeatureSettings("customModelData")),
    whitelistedWorlds(getFeatureSettings("whitelistedWorlds")),
    armorColor(getFeatureSettings("armorColor")),
    fireworkColor(getFeatureSettings("fireworkColor")),
    recognitions(getFeatureSettings("recognitions")),
    food(getFeatureSettings("food")),
    nutrition(getFeatureSettings("nutrition")),
    saturation(getFeatureSettings("saturation")),
    isMeat(getFeatureSettings("isMeat")),
    canAlwaysEat(getFeatureSettings("canAlwaysEat")),
    eatSeconds(getFeatureSettings("eatSeconds")),
    blockState(getFeatureSettings("blockState")),
    blockStatePlus(getFeatureSettings("blockStatePlus")),
    bundleContent(getFeatureSettings("bundleContent")),
    itemRarity(getFeatureSettings("itemRarity")),
    rarity(getFeatureSettings("rarity")),
    enableRarity(getFeatureSettings("enableRarity")),
    durability_features(getFeatureSettings("durability")),
    maxDurability(getFeatureSettings("maxDurability")),
    durability(getFeatureSettings("durability")),
    isDurabilityBasedOnUsage(getFeatureSettings("isDurabilityBasedOnUsage")),
    displayConditions(getFeatureSettings("displayConditions")),
    enableFeature(getFeatureSettings("enableFeature")),
    nbt(getFeatureSettings("nbt")),
    autoUpdateFeatures(getFeatureSettings("autoUpdateFeatures")),
    autoUpdateItem(getFeatureSettings("autoUpdateItem")),
    updateMaterial(getFeatureSettings("updateMaterial")),
    updateName(getFeatureSettings("updateName")),
    updateLore(getFeatureSettings("updateLore")),
    updateDurability(getFeatureSettings("updateDurability")),
    updateAttributes(getFeatureSettings("updateAttributes")),
    updateEnchants(getFeatureSettings("updateEnchants")),
    updateCustomModelData(getFeatureSettings("updateCustomModelData")),
    updateArmorSettings(getFeatureSettings("updateArmorSettings")),
    updateHiders(getFeatureSettings("updateHiders")),
    brewingStandFeatures(getFeatureSettings("brewingStandFeatures")),
    brewingStandSpeed(getFeatureSettings("brewingStandSpeed")),
    boundingBoxZones(getFeatureSettings("boundingBoxZones")),
    boundingBoxZone(getFeatureSettings("boundingBoxZone")),
    from(getFeatureSettings("from")),
    to(getFeatureSettings("to")),
    containerFeatures(getFeatureSettings("containerFeatures")),
    whitelistMaterials(getFeatureSettings("whitelistMaterials")),
    blacklistMaterials(getFeatureSettings("blacklistMaterials")),
    isLocked(getFeatureSettings("isLocked")),
    lockedName(getFeatureSettings("lockedName")),
    inventoryTitle(getFeatureSettings("inventoryTitle")),
    furnaceFeatures(getFeatureSettings("furnaceFeatures")),
    furnaceSpeed(getFeatureSettings("furnaceSpeed")),
    infiniteFuel(getFeatureSettings("infiniteFuel")),
    infiniteVisualLit(getFeatureSettings("infiniteVisualLit")),
    fortuneChance(getFeatureSettings("fortuneChance")),
    fortuneMultiplier(getFeatureSettings("fortuneMultiplier")),
    directionalFeatures(getFeatureSettings("directionalFeatures")),
    forceBlockFaceOnPlace(getFeatureSettings("forceBlockFaceOnPlace")),
    blockFaceOnPlace(getFeatureSettings("blockFaceOnPlace")),
    hopperFeatures(getFeatureSettings("hopperFeatures")),
    amountItemsTransferred(getFeatureSettings("amountItemsTransferred")),
    chiseledBookshelfFeatures(getFeatureSettings("chiseledBookshelfFeatures")),
    occupiedSlots(getFeatureSettings("occupiedSlots")),
    InteractionZoneFeatures(getFeatureSettings("InteractionZoneFeatures")),
    width(getFeatureSettings("width")),
    height(getFeatureSettings("height")),
    isCollidable(getFeatureSettings("isCollidable")),
    DisplayFeatures(getFeatureSettings("DisplayFeatures")),
    scale(getFeatureSettings("scale")),
    aligned(getFeatureSettings("aligned")),
    customPitch(getFeatureSettings("customPitch")),
    customY(getFeatureSettings("customY")),
    clickToBreak(getFeatureSettings("clickToBreak")),
    EXECUTABLEBLOCK(getFeatureSettings("EXECUTABLEBLOCK")),
    EXECUTABLEBLOCKPLACED(getFeatureSettings("EXECUTABLEBLOCKPLACED")),
    EXECUTABLEEVENT(getFeatureSettings("EXECUTABLEEVENT")),
    FURNITURE(getFeatureSettings("FURNITURE")),
    FURNITUREPLACED(getFeatureSettings("FURNITUREPLACED")),
    creationType(getFeatureSettings("creationType")),
    spawnerType(getFeatureSettings("spawnerType")),
    dropType(getFeatureSettings("dropType")),
    cancelGravity(getFeatureSettings("cancelGravity")),
    cancelLiquidDestroy(getFeatureSettings("cancelLiquidDestroy")),
    onlyBreakableWithEI(getFeatureSettings("onlyBreakableWithEI")),
    dropBlockIfItIsBroken(getFeatureSettings("dropBlockIfItIsBroken")),
    dropBlockWhenItExplodes(getFeatureSettings("dropBlockWhenItExplodes")),
    dropBlockWhenItBurns(getFeatureSettings("dropBlockWhenItBurns")),
    resetInternalDatasWhenBroken(getFeatureSettings("resetInternalDatasWhenBroken")),
    canBeMoved(getFeatureSettings("canBeMoved")),
    itemsAdderID(getFeatureSettings("itemsAdderID")),
    oraxenID(getFeatureSettings("oraxenID")),
    interactionRange(getFeatureSettings("interactionRange")),
    enabled(getFeatureSettings("enabled")),
    editorIcon(getFeatureSettings("editorIcon")),
    disabledWorlds(getFeatureSettings("disabledWorlds")),
    displayFeatures(getFeatureSettings("displayFeatures")),
    blockLight(getFeatureSettings("blockLight")),
    skyLight(getFeatureSettings("skyLight")),
    glowColor(getFeatureSettings("glowColor")),
    TRADE(getFeatureSettings("TRADE")),
    description(getFeatureSettings("description")),
    delayOfTrade(getFeatureSettings("delayOfTrade")),
    glowWhenTrade(getFeatureSettings("glowWhenTrade")),
    requiredObject(getFeatureSettings("requiredObject")),
    SCREEN(getFeatureSettings("SCREEN")),
    SCREENUNIT(getFeatureSettings("SCREENUNIT")),
    leverUUID(getFeatureSettings("leverUUID")),
    interactionUUID(getFeatureSettings("interactionUUID")),
    rotation(getFeatureSettings("rotation")),
    glowWhenPowered(getFeatureSettings("glowWhenPowered")),
    EXECUTABLELEVER(getFeatureSettings("EXECUTABLELEVER")),
    startDate(getFeatureSettings("startDate")),
    endDate(getFeatureSettings("endDate")),
    when(getFeatureSettings("when")),
    scheduleFeatures(getFeatureSettings("scheduleFeatures"));

    private final FeatureSettingsInterface settingsInterface;

    FeatureSettingsSCore(FeatureSettingsInterface settingsInterface) {
        this.settingsInterface = settingsInterface;
    }

    public static FeatureSettingsInterface[] getValues() {
        String locale = GeneralConfig.getInstance().getLocale();
        switch (locale){
            case "FR":
                return FeatureSettingsSCoreFR.values();
            case "EN":
                return FeatureSettingsSCoreEN.values();
            case "ES":
                return FeatureSettingsSCoreEN.values();
            case "HU":
                return FeatureSettingsSCoreEN.values();
            case "ptBR":
                return FeatureSettingsSCoreEN.values();
            case "DE":
                return FeatureSettingsSCoreEN.values();
            case "UK":
                return FeatureSettingsSCoreEN.values();
            case "RU":
                return FeatureSettingsSCoreRU.values();
            case "ZH":
                return FeatureSettingsSCoreZH.values();
            default:
                return FeatureSettingsSCoreEN.values();
        }
    }

    public static FeatureSettingsInterface getFeatureSettings(String configName) {
        FeatureSettingsInterface[] values = getValues();
        for (FeatureSettingsInterface value : values) {
            if (value.getName().equals(configName)) {
                return value;
            }
        }
        throw new IllegalArgumentException("No feature settings found for config name: " + configName);
    }

    @Override
    public String getName() {
        return settingsInterface.getName();
    }

    @Override
    public String getEditorName() {
        return settingsInterface.getEditorName();
    }

    @Override
    public String[] getEditorDescription() {
        String [] lines = settingsInterface.getEditorDescription();
        // Add into the last line the config name
        String [] newLines = new String[lines.length+1];
        for(int i = 0; i < lines.length; i++) {
            newLines[i] = lines[i];
        }
        newLines[lines.length] = "&8&o(" + settingsInterface.getName()+")";
        return newLines;
    }

    @Override
    public Material getEditorMaterial() {
        if(settingsInterface.getEditorMaterial() == null) return Material.LEVER;
        return settingsInterface.getEditorMaterial();
    }

    @Override
    public boolean isRequirePremium() {
        return settingsInterface.isRequirePremium();
    }
}
