name: SCore
author: Ssomar
version: ${project.version}
main: com.ssomar.score.SCore
api-version: 1.13
softdepend: [ProtocolLib, NBTAPI, PolymartHelper, Polymart, Vault, Multiverse-Core, WorldGuard, PlaceholderAPI, CoreProtect, DecentHolograms, HolographicDisplaysAPI, HolographicDisplays]
loadbefore: [ExecutableItems, SParkour, ExecutableBlocks, ExecutableEvents, CustomPiglinsTrades]
commands:
  score:
    description: score command
    usage: /<command> [ reload | inspect-loop ]
permissions:
  score.*:
    description: SCore permission
    default: op
    children:
      score.cmds: true
  score.cmds:
    description: Allows SCore commands
    default: op
    children:
      score.cmd.reload: true
      score.cmd.inspect-loop: true
  score.cmd.reload:
    description: Allows the command /score reload
  score.cmd.inspect-loop:
    description: Allows the command /score inspect-loop
folia-supported: true
