name: SCore
author: Ssomar
version: ${project.version}
main: com.ssomar.score.SCore
api-version: 1.13
softdepend: [ProtocolLib, NBTAPI, PolymartHelper, Polymart, Vault, Multiverse-Core, WorldGuard, PlaceholderAPI, DecentHolograms, HolographicDisplaysAPI, HolographicDisplays, MyWorlds, ExcellentClaims, packetevents]
loadbefore: [ExecutableItems, SParkour, ExecutableBlocks, ExecutableEvents, CustomPiglinsTrades]
commands:
  score:
    description: score command
    usage: /<command> [ reload | inspect-loop ]
permissions:
  score.*:
    description: SCore permission
    default: op
    children:
      score.cmds: true
  score.cmds:
    description: Allows SCore commands
    default: op
    children:
      score.cmd.reload: true
      score.cmd.inspect-loop: true
      score.cmd.particles-toggle: true
  score.cmd.reload:
    description: Allows the command /score reload
  score.cmd.inspect-loop:
    description: Allows the command /score inspect-loop
  score.cmd.particles-toggle:
    description: Allows the command /score particles-toggle (self)
folia-supported: true
libraries:
  - io.netty:netty-all:4.1.118.Final
  - net.kyori:adventure-text-minimessage:4.17.0
  - net.kyori:adventure-api:4.17.0
  - net.kyori:adventure-text-serializer-legacy:4.17.0
