package com.ssomar.scoretestrecode.features.custom.restrictions;

public enum RestrictionEnum {
    CANCEL_DROP,
    CANCEL_PLACE,

    CANCEL_TOOL_INTERACTIONS,
    CANCEL_CONSUMPTION,

    CANCEL_CRAFT,
    CANCEL_ALL_CRAFT,

    CANCEL_DEPOSIT_IN_CHEST,
    CANCEL_DEPOSIT_IN_FURNACE,
    CANCEL_STONE_CUTTER,
    CANCEL_ENCHANT,
    CANCEL_ANVIL,
    CANCEL_ACTION_RENAME_IN_ANVIL,
    CANCEL_ACTION_ENCHANT_IN_ANVIL,
    CANCEL_GRIND_STONE,
    CANCEL_ITEM_FRAME,
    CANCEL_SMITHING_TABLE,
    CANCEL_BREWING,
    CANCEL_BEACON,
    CANCEL_CARTOGRAPHY,
    CANCEL_COMPOSTER,
    CANCEL_DISPENSER,
    CANCEL_DROPPER,
    CANCEL_HOPPER,
    CANCEL_LECTERN,
    CANCEL_LOOM,

    CANCEL_MERCHANT,

    CANCEL_ITEM_BURN,
    CANCEL_ITEM_DELETE_BY_CACTUS,
    CANCEL_ITEM_DELETE_BY_LIGHTNING,

    CANCEL_SWAPHAND,
    LOCKED_INVENTORY;

}
