package com.ssomar.score.utils.emums;

public enum ResetSetting {
    NAME,
    LORE,
    DURABILITY,
    ATTRIBUTES,
    ENCHANTS,
    CUSTOM_MODEL_DATA,
    ARMOR_SETTINGS,
    USAGE,
    ITEM_RARITY,
    BOOK,
    EQUIPPABLE,
    REPAIRABLE,
    HIDERS,
    INSTRUMENT,
    TOOL_RULES,
    FIREWORK,
    FIREWORK_EXPLOSION,
    CONTAINER, HEAD, BANNER, FOOD, BUNDLE, BLOCK_STATE, CHARGED_PROJECTILES,


}
